stages:
  - build
  - test

cache:
  key: node_modules
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline
  
build:
  script:
    - npm install

test:
  script:
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-shared ../vetprovieh-shared
    - npm run test
